#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2012
if [[ -n "${ROTATE_SA_REMOTE}" ]] && [[ -d "${CONFIG_DIR}/rotate-sa" ]]; then
    echo "Rotating service account file for remote \"${ROTATE_SA_REMOTE}\"..."
    oldest_account=$(ls -t "${CONFIG_DIR}/rotate-sa" | tail -1)
    echo "Using file \"${oldest_account}\"."
    s6-setuidgid hotio rclone config update "${ROTATE_SA_REMOTE}" service_account_file "${CONFIG_DIR}/rotate-sa/${oldest_account}"
    s6-setuidgid hotio touch "${CONFIG_DIR}/rotate-sa/${oldest_account}"
fi
